# Generated by Django 2.0.7 on 2018-07-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisServicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='servicio',
            new_name='servicios',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
