# Generated by Django 2.0.7 on 2018-07-25 15:08

import DjangoMongoApp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField()),
                ('totalFactura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=75)),
                ('ciudad', models.CharField(max_length=75)),
                ('servicios', djongo.models.fields.EmbeddedModelField(model_container=DjangoMongoApp.models.Servicio, null=True)),
            ],
        ),
    ]
