# Generated by Django 2.0.7 on 2018-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('servicios', models.ManyToManyField(to='DjangoMongoApp.Servicio')),
            ],
        ),
    ]
