# Generated by Django 2.0.7 on 2018-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMongoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
