# Generated by Django 2.0.7 on 2018-08-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=35)),
                ('fecha', models.DateField()),
                ('totalFactura', models.FloatField()),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('ciudad', models.CharField(max_length=75)),
                ('servicios', models.ManyToManyField(to='MisServicios.Servicio')),
            ],
        ),
    ]
