# Generated by Django 2.0.7 on 2018-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciousuario',
            name='totalFactura',
            field=models.FloatField(null=True),
        ),
    ]
